// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func CreateTodo() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div hx-ext=\"add-todo-container\"><form hx-post=\"/todo\" hx-trigger=\"submit\" hx-target=\"#todo-list\" hx-target-error=\"#add-todo-error\" hx-swap=\"innerHTML\" class=\"flex flex-col items-start gap-2 font-mono\"><div class=\"w-full flex flex-col items-start gap-2\"><h1 class=\"text-sm font-semibold text-neutral-800\">create todo</h1><input type=\"text\" name=\"title\" placeholder=\"title\" autocomplete=\"off\" class=\"form-input w-full p-0.5 px-2 text-xs rounded-sm border border-neutral-800\" required> <input type=\"text\" name=\"description\" placeholder=\"desc\" autocomplete=\"off\" class=\"form-input w-full p-0.5 px-2 text-xs rounded-sm border border-neutral-800\"></div><button type=\"submit\" aria-label=\"Add Todo\" class=\"w-6 h-6 flex justify-center items-center bg-green-700 rounded shadow-sm focus:outline-none\"><svg class=\"w-6 h-6 text-white\" viewBox=\"0 0 24 24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><g id=\"SVGRepo_bgCarrier\" stroke-width=\"0\"></g> <g id=\"SVGRepo_tracerCarrier\" stroke-linecap=\"round\" stroke-linejoin=\"round\"></g> <g id=\"SVGRepo_iconCarrier\"><path d=\"M6 12H18M12 6V18\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"></path></g></svg> <span class=\"sr-only\">Add Todo</span></button></form><div id=\"add-todo-error\"></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
